/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;

import com.knalpot;
import com.ConvertKnalpotToObject;

import com.transaksi;
import com.ConvertTransaksiToObject;

import com.admin;
import com.ConvertAdminToObject;

import com.pegawai;
import com.ConvertPegawaiToObject;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;


import javax.swing.JOptionPane;

/**
 *
 * @author Mesin Tempur
 */
public class formAdmin extends javax.swing.JFrame {

    /**
     * Creates new form formAdmin
     */
    public formAdmin() {
        initComponents();
        setDataKnalpot();
        setDataTransaksi();
        setDataAdmin();
        setDataPegawai();
    }
    
    private void setDataPegawai(){
        ConvertPegawaiToObject cpto = new ConvertPegawaiToObject();
        String[][]dataPegawai = cpto.getPegawai();
            tabelpegawai.setModel(new javax.swing.table.DefaultTableModel(
                    dataPegawai, new String[]{
                        "Nama Pegawai", "Username Pegawai", "Password Pegawai"
                    }
            ));
    }
    private void setDataAdmin(){
        ConvertAdminToObject cato = new ConvertAdminToObject();
        String[][]dataAdmin = cato.getAdmin();
           tabeladmin.setModel(new javax.swing.table.DefaultTableModel(
                   dataAdmin, new String[]{
                       "Nama Admin", "Username Admin", "Password Admin"
                   }
           ));
    }
    
    private void setDataKnalpot(){
        
        ConvertKnalpotToObject ckto = new ConvertKnalpotToObject();
        String[][]dataKnalpot = ckto.getknalpot();
            tabelKnalpot.setModel(new javax.swing.table.DefaultTableModel(
           dataKnalpot, new String[]{
               "ID Knalpot", "Nama Knalpot", "Harga Knalpot"
           }  
                   ));
    }
    
    private void setDataTransaksi(){
        ConvertTransaksiToObject ctto = new ConvertTransaksiToObject();
        String[][]DataTransaksi = ctto.gettransaksi();
            tabeltransaksi.setModel(new javax.swing.table.DefaultTableModel(
                    DataTransaksi, new String[]{
                        "ID Transaksi", "Tanggal Beli", "Nama Pembeli", "Barang yg Dibeli", "Jumlah Beli", "Total Harga"
                    }
            ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnknp = new javax.swing.JButton();
        btntrs = new javax.swing.JButton();
        btnadm = new javax.swing.JButton();
        btnpgw = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnlUtama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlKnalpot = new javax.swing.JPanel();
        pnlInputKnalpot = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnamaknalpot = new javax.swing.JTextField();
        txthargaknalpot = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtidknalpot = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        pnlTabelKnalpot = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKnalpot = new javax.swing.JTable();
        pnlTransaksi = new javax.swing.JPanel();
        pnlInputTransaksi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnamapembeli = new javax.swing.JTextField();
        txtjumlahbeli = new javax.swing.JTextField();
        txthargatotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnCreatetr = new javax.swing.JButton();
        btnupdatecr = new javax.swing.JButton();
        btndeletetr = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtidtransaksi = new javax.swing.JTextField();
        txttanggal_beli = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtnamabarang = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        pnlTabelTransaksi = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeltransaksi = new javax.swing.JTable();
        pnlAdmin = new javax.swing.JPanel();
        pnlInputAdmin = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtnamaAdmin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUsernameAdmin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPasswordAdmin = new javax.swing.JTextField();
        btnCreateAdmin = new javax.swing.JButton();
        btnUpdateAdmin = new javax.swing.JButton();
        btnDeleteAdmin = new javax.swing.JButton();
        pnlTabelAdmin = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabeladmin = new javax.swing.JTable();
        pnlPegawai = new javax.swing.JPanel();
        pnlInputPegawai = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtnamaPegawai = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtusernamepegawai = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPasswordPegawai = new javax.swing.JTextField();
        btnCreatePegawai = new javax.swing.JButton();
        btnUpdatePegawai = new javax.swing.JButton();
        btnDeletePegawai = new javax.swing.JButton();
        pnlTabelPegawai = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelpegawai = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Admin");
        setBackground(new java.awt.Color(0, 153, 255));

        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setRollover(true);

        btnknp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/knalpoticon.png"))); // NOI18N
        btnknp.setText("Data Knalpot");
        btnknp.setFocusable(false);
        btnknp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnknp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnknp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnknpActionPerformed(evt);
            }
        });
        jToolBar1.add(btnknp);

        btntrs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transaksi.png"))); // NOI18N
        btntrs.setText("Data Transaksi");
        btntrs.setFocusable(false);
        btntrs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btntrs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btntrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrsActionPerformed(evt);
            }
        });
        jToolBar1.add(btntrs);

        btnadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pegawai.png"))); // NOI18N
        btnadm.setText("Data User Admin");
        btnadm.setFocusable(false);
        btnadm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnadm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadmActionPerformed(evt);
            }
        });
        jToolBar1.add(btnadm);

        btnpgw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pelanggan.png"))); // NOI18N
        btnpgw.setText("Data User Pegawai");
        btnpgw.setFocusable(false);
        btnpgw.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpgw.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnpgw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpgwActionPerformed(evt);
            }
        });
        jToolBar1.add(btnpgw);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jButton1.setText("LogOut");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        pnlUtama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlUtama.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selamat Datang di Form Admin!");
        pnlUtama.add(jLabel1, "card2");

        pnlKnalpot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlInputKnalpot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlInputKnalpot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nama Knalpot");
        pnlInputKnalpot.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setText("Harga Knalpot");
        pnlInputKnalpot.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtnamaknalpot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaknalpotActionPerformed(evt);
            }
        });
        pnlInputKnalpot.add(txtnamaknalpot, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 120, -1));
        pnlInputKnalpot.add(txthargaknalpot, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 120, -1));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        pnlInputKnalpot.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlInputKnalpot.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlInputKnalpot.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel14.setText("ID Knalpot");
        pnlInputKnalpot.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtidknalpot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtidknalpotMouseClicked(evt);
            }
        });
        pnlInputKnalpot.add(txtidknalpot, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, -1));

        jButton2.setText("Copy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlInputKnalpot.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        pnlTabelKnalpot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabelKnalpot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKnalpot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKnalpotMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKnalpot);

        javax.swing.GroupLayout pnlTabelKnalpotLayout = new javax.swing.GroupLayout(pnlTabelKnalpot);
        pnlTabelKnalpot.setLayout(pnlTabelKnalpotLayout);
        pnlTabelKnalpotLayout.setHorizontalGroup(
            pnlTabelKnalpotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelKnalpotLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        pnlTabelKnalpotLayout.setVerticalGroup(
            pnlTabelKnalpotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelKnalpotLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlKnalpotLayout = new javax.swing.GroupLayout(pnlKnalpot);
        pnlKnalpot.setLayout(pnlKnalpotLayout);
        pnlKnalpotLayout.setHorizontalGroup(
            pnlKnalpotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKnalpotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputKnalpot, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabelKnalpot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlKnalpotLayout.setVerticalGroup(
            pnlKnalpotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKnalpotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKnalpotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTabelKnalpot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInputKnalpot, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlUtama.add(pnlKnalpot, "cardKnalpot");

        pnlTransaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlInputTransaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Nama Pembeli");

        jLabel5.setText("Jumlah Beli");

        jLabel6.setText("Tanggal Beli");

        jLabel7.setText("Harga Total");

        btnCreatetr.setText("Create");
        btnCreatetr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatetrActionPerformed(evt);
            }
        });

        btnupdatecr.setText("Update");
        btnupdatecr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatecrActionPerformed(evt);
            }
        });

        btndeletetr.setText("Delete");
        btndeletetr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletetrActionPerformed(evt);
            }
        });

        jLabel15.setText("ID Transaksi");

        txtidtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidtransaksiActionPerformed(evt);
            }
        });

        jLabel16.setText("Barang yg Dibeli");

        txtnamabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamabarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInputTransaksiLayout = new javax.swing.GroupLayout(pnlInputTransaksi);
        pnlInputTransaksi.setLayout(pnlInputTransaksiLayout);
        pnlInputTransaksiLayout.setHorizontalGroup(
            pnlInputTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlInputTransaksiLayout.createSequentialGroup()
                        .addGroup(pnlInputTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCreatetr)
                            .addGroup(pnlInputTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)))
                        .addGroup(pnlInputTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInputTransaksiLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(pnlInputTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtidtransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(txthargatotal)
                                    .addComponent(txtnamapembeli)
                                    .addComponent(txtjumlahbeli)
                                    .addComponent(txttanggal_beli)))
                            .addGroup(pnlInputTransaksiLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnlInputTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlInputTransaksiLayout.createSequentialGroup()
                                        .addComponent(btnupdatecr)
                                        .addGap(18, 18, 18)
                                        .addComponent(btndeletetr))))))
                    .addComponent(jLabel15)
                    .addGroup(pnlInputTransaksiLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txtnamabarang)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlInputTransaksiLayout.setVerticalGroup(
            pnlInputTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputTransaksiLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlInputTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtidtransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlInputTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txttanggal_beli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlInputTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtnamapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlInputTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlInputTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtjumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlInputTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txthargatotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(pnlInputTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreatetr)
                    .addComponent(btnupdatecr)
                    .addComponent(btndeletetr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlTabelTransaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabeltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeltransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeltransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeltransaksi);

        javax.swing.GroupLayout pnlTabelTransaksiLayout = new javax.swing.GroupLayout(pnlTabelTransaksi);
        pnlTabelTransaksi.setLayout(pnlTabelTransaksiLayout);
        pnlTabelTransaksiLayout.setHorizontalGroup(
            pnlTabelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
        );
        pnlTabelTransaksiLayout.setVerticalGroup(
            pnlTabelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlTransaksiLayout = new javax.swing.GroupLayout(pnlTransaksi);
        pnlTransaksi.setLayout(pnlTransaksiLayout);
        pnlTransaksiLayout.setHorizontalGroup(
            pnlTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransaksiLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pnlInputTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTransaksiLayout.setVerticalGroup(
            pnlTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTabelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInputTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlUtama.add(pnlTransaksi, "cardTransaksi");

        pnlAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlInputAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Nama Admin");

        txtnamaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaAdminActionPerformed(evt);
            }
        });

        jLabel9.setText("Username Admin");

        jLabel10.setText("Password Admin");

        btnCreateAdmin.setText("Create");
        btnCreateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAdminActionPerformed(evt);
            }
        });

        btnUpdateAdmin.setText("Update");
        btnUpdateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAdminActionPerformed(evt);
            }
        });

        btnDeleteAdmin.setText("Delete");
        btnDeleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInputAdminLayout = new javax.swing.GroupLayout(pnlInputAdmin);
        pnlInputAdmin.setLayout(pnlInputAdminLayout);
        pnlInputAdminLayout.setHorizontalGroup(
            pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputAdminLayout.createSequentialGroup()
                .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputAdminLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPasswordAdmin))
                    .addGroup(pnlInputAdminLayout.createSequentialGroup()
                        .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnamaAdmin)
                            .addComponent(txtUsernameAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))
                    .addGroup(pnlInputAdminLayout.createSequentialGroup()
                        .addComponent(btnCreateAdmin)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateAdmin)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteAdmin)))
                .addContainerGap())
        );
        pnlInputAdminLayout.setVerticalGroup(
            pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtnamaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtUsernameAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtPasswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateAdmin)
                    .addComponent(btnUpdateAdmin)
                    .addComponent(btnDeleteAdmin))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pnlTabelAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabeladmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeladmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeladminMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabeladmin);

        javax.swing.GroupLayout pnlTabelAdminLayout = new javax.swing.GroupLayout(pnlTabelAdmin);
        pnlTabelAdmin.setLayout(pnlTabelAdminLayout);
        pnlTabelAdminLayout.setHorizontalGroup(
            pnlTabelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTabelAdminLayout.setVerticalGroup(
            pnlTabelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTabelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTabelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInputAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlUtama.add(pnlAdmin, "cardAdmin");

        pnlPegawai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlInputPegawai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText("Nama Pegawai");

        txtnamaPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaPegawaiActionPerformed(evt);
            }
        });

        jLabel12.setText("Username Pegawai");

        txtusernamepegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernamepegawaiActionPerformed(evt);
            }
        });

        jLabel13.setText("Password Pegawai");

        btnCreatePegawai.setText("Create");
        btnCreatePegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePegawaiActionPerformed(evt);
            }
        });

        btnUpdatePegawai.setText("Update");
        btnUpdatePegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePegawaiActionPerformed(evt);
            }
        });

        btnDeletePegawai.setText("Delete");
        btnDeletePegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePegawaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInputPegawaiLayout = new javax.swing.GroupLayout(pnlInputPegawai);
        pnlInputPegawai.setLayout(pnlInputPegawaiLayout);
        pnlInputPegawaiLayout.setHorizontalGroup(
            pnlInputPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputPegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputPegawaiLayout.createSequentialGroup()
                        .addGroup(pnlInputPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(pnlInputPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPasswordPegawai)
                            .addComponent(txtnamaPegawai)
                            .addComponent(txtusernamepegawai)))
                    .addGroup(pnlInputPegawaiLayout.createSequentialGroup()
                        .addComponent(btnCreatePegawai)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdatePegawai)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletePegawai)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlInputPegawaiLayout.setVerticalGroup(
            pnlInputPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputPegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnamaPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(30, 30, 30)
                .addGroup(pnlInputPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtusernamepegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnlInputPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtPasswordPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlInputPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreatePegawai)
                    .addComponent(btnUpdatePegawai)
                    .addComponent(btnDeletePegawai))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pnlTabelPegawai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabelpegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelpegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpegawaiMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelpegawai);

        javax.swing.GroupLayout pnlTabelPegawaiLayout = new javax.swing.GroupLayout(pnlTabelPegawai);
        pnlTabelPegawai.setLayout(pnlTabelPegawaiLayout);
        pnlTabelPegawaiLayout.setHorizontalGroup(
            pnlTabelPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelPegawaiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTabelPegawaiLayout.setVerticalGroup(
            pnlTabelPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelPegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlPegawaiLayout = new javax.swing.GroupLayout(pnlPegawai);
        pnlPegawai.setLayout(pnlPegawaiLayout);
        pnlPegawaiLayout.setHorizontalGroup(
            pnlPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTabelPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPegawaiLayout.setVerticalGroup(
            pnlPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTabelPegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInputPegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlUtama.add(pnlPegawai, "cardPegawai");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnknpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnknpActionPerformed
    cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardKnalpot");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnknpActionPerformed

    private void txtnamaknalpotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaknalpotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaknalpotActionPerformed

    private void btntrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrsActionPerformed
    cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardTransaksi");
        // TODO add your handling code here:
    }//GEN-LAST:event_btntrsActionPerformed

    private void btnCreatetrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatetrActionPerformed
 
        String id_transaksi = txtidtransaksi.getText();
        String tanggal_beli = txttanggal_beli.getText();
        String nama_pembeli = txtnamapembeli.getText();
        String barang_dibeli = txtnamabarang.getText();
        String strjumlah_beli = txtjumlahbeli.getText();
        String strharga_total = txthargatotal.getText();
        int jumlah_beli = Integer.parseInt(strjumlah_beli);
        int harga_total = Integer.parseInt(strharga_total);
        transaksi tr = new transaksi(id_transaksi, tanggal_beli, nama_pembeli, barang_dibeli, jumlah_beli, harga_total);
        exec.executeTransaksi etransaksi = new exec.executeTransaksi();
        int hasil = etransaksi.insertData(tr);
        if(hasil > 0){
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setDataTransaksi();
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        }       

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreatetrActionPerformed

    private void txtnamaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaAdminActionPerformed

    private void txtnamaPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaPegawaiActionPerformed

    private void txtusernamepegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernamepegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernamepegawaiActionPerformed

    private void btnadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadmActionPerformed
    cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardAdmin");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnadmActionPerformed

    private void btnpgwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpgwActionPerformed
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardPegawai");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpgwActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String id_knalpot = txtidknalpot.getText();
        String nama_knalpot = txtnamaknalpot.getText();
        String strharga_knalpot = txthargaknalpot.getText();
        int harga_knalpot = Integer.parseInt(strharga_knalpot);
        knalpot kp = new knalpot(id_knalpot, nama_knalpot, harga_knalpot);
        exec.executeKnalpot eKnalpot = new exec.executeKnalpot();
        int hasil = eKnalpot.insertData(kp);
        if(hasil >0){
                 JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setDataKnalpot();   
    }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        } 
    }//GEN-LAST:event_btnCreateActionPerformed

    private void tabelKnalpotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKnalpotMouseClicked
        int row = tabelKnalpot.getSelectedRow();
        String id_knalpot = tabelKnalpot.getValueAt(row, 0).toString();
        String nama_knalpot = tabelKnalpot.getValueAt(row, 1).toString();
        String harga_knalpot = tabelKnalpot.getValueAt(row, 2).toString();
        txtidknalpot.setText(id_knalpot);
        txtnamaknalpot.setText(nama_knalpot);
        txthargaknalpot.setText(harga_knalpot);

        // TODO add your handling code here:
    }//GEN-LAST:event_tabelKnalpotMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String id_knalpot = txtidknalpot.getText();
        String nama_knalpot = txtnamaknalpot.getText();
        String strharga_knalpot = txthargaknalpot.getText();
        int harga_knalpot = Integer.parseInt(strharga_knalpot);
        knalpot kp = new knalpot(id_knalpot, nama_knalpot, harga_knalpot);
        exec.executeKnalpot eKnalpot = new exec.executeKnalpot();
        int hasil = eKnalpot.ubahData(kp);
        if(hasil >0){
                 JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setDataKnalpot();   
          
    }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        } 
         
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String id_knalpot = txtidknalpot.getText();
        exec.executeKnalpot eknalpot = new exec.executeKnalpot();
        int hasil = eknalpot.hapusData(id_knalpot);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setDataKnalpot();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtidtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidtransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidtransaksiActionPerformed

    private void tabeltransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeltransaksiMouseClicked
        int row = tabeltransaksi.getSelectedRow();
        String id_transaksi = tabeltransaksi.getValueAt(row, 0).toString();
        String tanggal_beli = tabeltransaksi.getValueAt(row, 1).toString();
        String nama_pembeli = tabeltransaksi.getValueAt(row, 2).toString();
        String barang_dibeli = tabeltransaksi.getValueAt(row, 3).toString();
        String jumlah_beli = tabeltransaksi.getValueAt(row, 4).toString();
        String harga_total = tabeltransaksi.getValueAt(row, 5).toString();
        //this.id_knalpot = Integer.parseint(id_knalpot)
        txtidtransaksi.setText(id_transaksi);
        txttanggal_beli.setText(tanggal_beli);
        txtnamapembeli.setText(nama_pembeli);
        txtnamabarang.setText(barang_dibeli);
        txtjumlahbeli.setText(jumlah_beli);
        txthargatotal.setText(harga_total);


        // TODO add your handling code here:
    }//GEN-LAST:event_tabeltransaksiMouseClicked

    private void txtnamabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamabarangActionPerformed

    private void btnupdatecrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatecrActionPerformed
       
        String id_transaksi = txtidtransaksi.getText();
        String tanggal_beli = txttanggal_beli.getText();
        String nama_pembeli = txtnamapembeli.getText();
        String barang_dibeli = txtnamabarang.getText();
        String strjumlah_beli = txtjumlahbeli.getText();
        String strharga_total = txthargatotal.getText();
        int jumlah_beli = Integer.parseInt(strjumlah_beli);
        int harga_total = Integer.parseInt(strharga_total);
        transaksi tr = new transaksi(id_transaksi, tanggal_beli, nama_pembeli, barang_dibeli, jumlah_beli, harga_total);
        exec.executeTransaksi etransaksi = new exec.executeTransaksi();
        int hasil = etransaksi.ubahData(tr);
        if(hasil > 0){
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setDataTransaksi();
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        }       

        // TODO add your handling code here:
    }//GEN-LAST:event_btnupdatecrActionPerformed

    private void btndeletetrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletetrActionPerformed
        String id_transaksi = txtidtransaksi.getText();
        exec.executeTransaksi etransaksi = new exec.executeTransaksi();
        int hasil = etransaksi.hapusData(id_transaksi);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setDataTransaksi();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeletetrActionPerformed

    private void tabeladminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeladminMouseClicked
       
        int row = tabeladmin.getSelectedRow();
        String nama_admin = tabeladmin.getValueAt(row, 0).toString();
        String username = tabeladmin.getValueAt(row, 1).toString();
        String password = tabeladmin.getValueAt(row, 2).toString();
        //this.id_knalpot = Integer.parseint(id_knalpot)
        txtnamaAdmin.setText(nama_admin);
        txtUsernameAdmin.setText(username);
        txtPasswordAdmin.setText(password);

        // TODO add your handling code here:
    }//GEN-LAST:event_tabeladminMouseClicked

    private void btnCreateAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAdminActionPerformed
        String nama_admin = txtnamaAdmin.getText();
        String username = txtUsernameAdmin.getText();
        String password = txtPasswordAdmin.getText();
        admin ad = new admin(nama_admin, username, password);
        exec.executeAdmin eAdmin = new exec.executeAdmin();
        int hasil = eAdmin.insertData(ad);

        if(hasil >0){
                 JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setDataAdmin();   
    }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        } 
      // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateAdminActionPerformed

    private void btnUpdateAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAdminActionPerformed
        String nama_admin = txtnamaAdmin.getText();
        String username = txtUsernameAdmin.getText();
        String password = txtPasswordAdmin.getText();
        admin ad = new admin(nama_admin, username, password);
        exec.executeAdmin eAdmin = new exec.executeAdmin();
        int hasil = eAdmin.ubahData(ad);
        if(hasil >0){
                 JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setDataAdmin();   
    }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        } 
    }//GEN-LAST:event_btnUpdateAdminActionPerformed

    private void btnDeleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAdminActionPerformed
        String username = txtUsernameAdmin.getText();
        exec.executeAdmin eadmin = new exec.executeAdmin();
        int hasil = eadmin.hapusData(username);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setDataAdmin();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
    }//GEN-LAST:event_btnDeleteAdminActionPerformed

    private void btnCreatePegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePegawaiActionPerformed
        String nama_pegawai = txtnamaPegawai.getText();
        String username = txtusernamepegawai.getText();
        String password = txtPasswordPegawai.getText();
        pegawai pg = new pegawai(nama_pegawai, username, password);
        exec.executePegawai ePegawai = new exec.executePegawai();
        int hasil = ePegawai.insertData(pg);

        if(hasil >0){
                 JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setDataPegawai();   
    }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        } 
    }//GEN-LAST:event_btnCreatePegawaiActionPerformed

    private void tabelpegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpegawaiMouseClicked
        int row = tabelpegawai.getSelectedRow();
        String nama_pegawai = tabelpegawai.getValueAt(row, 0).toString();
        String username = tabelpegawai.getValueAt(row, 1).toString();
        String password = tabelpegawai.getValueAt(row, 2).toString();
        
        txtnamaPegawai.setText(nama_pegawai);
        txtusernamepegawai.setText(username);
        txtPasswordPegawai.setText(password);
    }//GEN-LAST:event_tabelpegawaiMouseClicked

    private void btnUpdatePegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePegawaiActionPerformed
        String nama_pegawai = txtnamaPegawai.getText();
        String username = txtusernamepegawai.getText();
        String password = txtPasswordPegawai.getText();
        pegawai pg = new pegawai(nama_pegawai, username, password);
        exec.executePegawai ePegawai = new exec.executePegawai();
        int hasil = ePegawai.ubahData(pg);

        if(hasil >0){
                 JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setDataPegawai();   
    }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdatePegawaiActionPerformed

    private void btnDeletePegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePegawaiActionPerformed
        String username = txtusernamepegawai.getText();
        exec.executePegawai ePegawai = new exec.executePegawai();
        int hasil = ePegawai.hapusData(username);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setDataPegawai();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
    }//GEN-LAST:event_btnDeletePegawaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                new formLoginPilihan().setVisible(true);
                dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtidknalpotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidknalpotMouseClicked
      
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidknalpotMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        StringSelection stringSelection = new StringSelection (txtidknalpot.getText());
        Clipboard clpbrd = Toolkit.getDefaultToolkit ().getSystemClipboard ();
        clpbrd.setContents (stringSelection, null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formAdmin().setVisible(true);
            }
        });
    }
    private CardLayout cl;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateAdmin;
    private javax.swing.JButton btnCreatePegawai;
    private javax.swing.JButton btnCreatetr;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteAdmin;
    private javax.swing.JButton btnDeletePegawai;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateAdmin;
    private javax.swing.JButton btnUpdatePegawai;
    private javax.swing.JButton btnadm;
    private javax.swing.JButton btndeletetr;
    private javax.swing.JButton btnknp;
    private javax.swing.JButton btnpgw;
    private javax.swing.JButton btntrs;
    private javax.swing.JButton btnupdatecr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlInputAdmin;
    private javax.swing.JPanel pnlInputKnalpot;
    private javax.swing.JPanel pnlInputPegawai;
    private javax.swing.JPanel pnlInputTransaksi;
    private javax.swing.JPanel pnlKnalpot;
    private javax.swing.JPanel pnlPegawai;
    private javax.swing.JPanel pnlTabelAdmin;
    private javax.swing.JPanel pnlTabelKnalpot;
    private javax.swing.JPanel pnlTabelPegawai;
    private javax.swing.JPanel pnlTabelTransaksi;
    private javax.swing.JPanel pnlTransaksi;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JTable tabelKnalpot;
    private javax.swing.JTable tabeladmin;
    private javax.swing.JTable tabelpegawai;
    private javax.swing.JTable tabeltransaksi;
    private javax.swing.JTextField txtPasswordAdmin;
    private javax.swing.JTextField txtPasswordPegawai;
    private javax.swing.JTextField txtUsernameAdmin;
    private javax.swing.JTextField txthargaknalpot;
    private javax.swing.JTextField txthargatotal;
    private javax.swing.JTextField txtidknalpot;
    private javax.swing.JTextField txtidtransaksi;
    private javax.swing.JTextField txtjumlahbeli;
    private javax.swing.JTextField txtnamaAdmin;
    private javax.swing.JTextField txtnamaPegawai;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txtnamaknalpot;
    private javax.swing.JTextField txtnamapembeli;
    private javax.swing.JTextField txttanggal_beli;
    private javax.swing.JTextField txtusernamepegawai;
    // End of variables declaration//GEN-END:variables
}
