/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.transaksi;
import com.ConvertTransaksiToObject;
import db.ConnectionManager;
import java.awt.print.PrinterException;
import perhitungan.hitung;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Mesin Tempur
 */

public class formKasir extends javax.swing.JFrame {
ConnectionManager conMan = new ConnectionManager();
Connection con = conMan.logOn();
    hitung htg = new hitung();
    public formKasir() {
        initComponents();
        setDataTransaksi();
        hargaknalpot();
    }
    
    public void hargaknalpot(){
        try{
            String query = "select * from knalpot";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(query);
            while(rs.next()){
                cbbbarang.addItem(rs.getString("nama_knalpot"));
            }
        }catch(SQLException e){
            
        }
    }
     private void setDataTransaksi(){
        ConvertTransaksiToObject ctto = new ConvertTransaksiToObject();
        String[][]DataTransaksi = ctto.gettransaksi();
            tabeltr.setModel(new javax.swing.table.DefaultTableModel(
                    DataTransaksi, new String[]{
                        "ID Transaksi", "Tanggal Beli", "Nama Pembeli", "Knalpot yg Dibeli", "Jumlah Beli", "Harga Total"
                    }
            ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrn = new javax.swing.JPanel();
        panelutama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeltr = new javax.swing.JTable();
        panelinput = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtidtr = new javax.swing.JTextField();
        txttglbeli = new javax.swing.JTextField();
        txtnamapembeli = new javax.swing.JTextField();
        cbbbarang = new javax.swing.JComboBox<>();
        txtjmlbeli = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txttotalharga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txthargasat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        panelbon = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        btnprint = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasir");
        setBackground(new java.awt.Color(51, 51, 255));

        bgrn.setBackground(new java.awt.Color(0, 153, 153));

        panelutama.setForeground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel1.setText("Kasir Toko Cengsknalpot");

        tabeltr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabeltr);

        panelinput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelinput.setForeground(new java.awt.Color(0, 153, 204));

        jLabel2.setText("ID Transaksi");

        jLabel3.setText("Tanggal Beli");

        jLabel4.setText("Nama Pembeli");

        jLabel5.setText("Knalpot yang dibeli");

        jLabel6.setText("Jumlah beli");

        jLabel7.setText("Total Harga");

        cbbbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbbarangActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Hitung Total Harga");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel8.setText("Input Data");

        jLabel10.setText("Harga Satuan");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sakura.jpg"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelinputLayout = new javax.swing.GroupLayout(panelinput);
        panelinput.setLayout(panelinputLayout);
        panelinputLayout.setHorizontalGroup(
            panelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelinputLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel7)
                                .addGap(64, 64, 64)
                                .addComponent(txttotalharga, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                            .addGroup(panelinputLayout.createSequentialGroup()
                                .addGroup(panelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addGroup(panelinputLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel11)))
                                .addGap(32, 32, 32)
                                .addGroup(panelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtidtr)
                                    .addComponent(txttglbeli)
                                    .addComponent(txtnamapembeli)
                                    .addComponent(cbbbarang, 0, 131, Short.MAX_VALUE)
                                    .addComponent(txtjmlbeli)
                                    .addComponent(txthargasat)
                                    .addComponent(txtnama))))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        panelinputLayout.setVerticalGroup(
            panelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinputLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(panelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtidtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txttglbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtnamapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbbbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(25, 25, 25)
                .addGroup(panelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtjmlbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(panelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txttotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelinputLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(53, 53, 53))
                    .addGroup(panelinputLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthargasat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        panelbon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel9.setText("Struk");

        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/print.png"))); // NOI18N
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelbonLayout = new javax.swing.GroupLayout(panelbon);
        panelbon.setLayout(panelbonLayout);
        panelbonLayout.setHorizontalGroup(
            panelbonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelbonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(panelbonLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelbonLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(btnprint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelbonLayout.setVerticalGroup(
            panelbonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbonLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnprint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelutamaLayout = new javax.swing.GroupLayout(panelutama);
        panelutama.setLayout(panelutamaLayout);
        panelutamaLayout.setHorizontalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelutamaLayout.createSequentialGroup()
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelutamaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelbon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelutamaLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelutamaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(210, 210, 210))
        );
        panelutamaLayout.setVerticalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelutamaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(25, 25, 25)
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelinput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelbon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout bgrnLayout = new javax.swing.GroupLayout(bgrn);
        bgrn.setLayout(bgrnLayout);
        bgrnLayout.setHorizontalGroup(
            bgrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgrnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelutama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bgrnLayout.setVerticalGroup(
            bgrnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgrnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelutama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgrn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int total_harga;
        total_harga = htg.totalharga(Integer.parseInt(txthargasat.getText()), Integer.parseInt(txtjmlbeli.getText()));
        txttotalharga.setText(Integer.toString(total_harga));
        String id_transaksi = txtidtr.getText();
        String tanggal_beli = txttglbeli.getText();
        String nama_pembeli = txtnamapembeli.getText();
        String barang_dibeli = (String) cbbbarang.getSelectedItem();
        String strjumlah_beli = txtjmlbeli.getText();
        String strharga_total = txttotalharga.getText();
        int jumlah_beli = Integer.parseInt(strjumlah_beli);
        int harga_total = Integer.parseInt(strharga_total);
        transaksi tr = new transaksi(id_transaksi, tanggal_beli, nama_pembeli, barang_dibeli, jumlah_beli, harga_total);
        exec.executeTransaksi etransaksi = new exec.executeTransaksi();
        int hasil = etransaksi.insertData(tr);
        if(hasil > 0){
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setDataTransaksi();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        }       
        String id = txtidtr.getText();
        String tgl = txttglbeli.getText();
        String nama = txtnamapembeli.getText();
        String brg = (String) cbbbarang.getSelectedItem();
        String jmlbeli = txtjmlbeli.getText();
        String harsat = txthargasat.getText();
        String hartot = txttotalharga.getText();
            jTextArea1.append("-----------------------------------------------------------------------------------------------------------------");
            jTextArea1.append("\n");
            jTextArea1.append("                                                            CengsKnalpot                                         ");
            jTextArea1.append("\n");
            jTextArea1.append("                                     Jalan Pungkur Nomor 35. Kota Bandung.                                       ");
            jTextArea1.append("\n");
            jTextArea1.append("                                                 Telepon : 085315489655                                          ");
            jTextArea1.append("\n");
            jTextArea1.append("                                           Email : cengsknalpot@gmail.com                                        ");
            jTextArea1.append("\n");
            jTextArea1.append("-----------------------------------------------------------------------------------------------------------------");
            jTextArea1.append("\n");
            jTextArea1.append("Tanggal Pembelian : "+tgl);
            jTextArea1.append("\n");
            jTextArea1.append("ID Nota : "+id);
            jTextArea1.append("\n");            
            jTextArea1.append("Nama Pembeli : "+nama);
            jTextArea1.append("\n");
            jTextArea1.append("-----------------------------------------------------------------------------------------------------------------");
            jTextArea1.append("\n");
            jTextArea1.append("Knalpot yang Dibeli: "+brg);
            jTextArea1.append("\n");
            jTextArea1.append("Harga Satuan: Rp. "+harsat);
            jTextArea1.append("\n");
            jTextArea1.append("Total Beli : "+jmlbeli);
            jTextArea1.append("\n");
            jTextArea1.append("-----------------------------------------------------------------------------------------------------------------");
            jTextArea1.append("\n");
            jTextArea1.append("Total Harga : Rp. "+hartot);
            jTextArea1.append("\n");
            jTextArea1.append("-----------------------------------------------------------------------------------------------------------------");
            jTextArea1.append("\n");
            jTextArea1.append("                                            Terima Kasih Telah Berbelanja                                        ");
            jTextArea1.append("\n");
            jTextArea1.append("-----------------------------------------------------------------------------------------------------------------");
            jTextArea1.append("\n");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbbbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbbarangActionPerformed
//       try{
//            String query="select * from knalpot where nama_knalpot='SAKURA'";
//            Statement stm = con.createStatement();
//            ResultSet rs = stm.executeQuery(query);
//            
//            while(rs.next())
//            {
//                txthargasat.setText(""+rs.getString("harga_knalpot"));
//            }
//        }catch(Exception e){
//            
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbbarangActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                new formLoginPilihan().setVisible(true);
                dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        try {
            jTextArea1.print();
            // TODO add your handling code here:
        } catch (PrinterException ex) {
            Logger.getLogger(formKasir.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnprintActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
      try{
            String query="select * from knalpot where nama_knalpot='SAKURA'";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(query);
            
            while(rs.next())
            {
                txtnama.setText(""+rs.getString("nama_knalpot"));
                txthargasat.setText(""+rs.getString("harga_knalpot"));
                
            }
        }catch(Exception e){
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgrn;
    private javax.swing.JButton btnprint;
    private javax.swing.JComboBox<String> cbbbarang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelbon;
    private javax.swing.JPanel panelinput;
    private javax.swing.JPanel panelutama;
    private javax.swing.JTable tabeltr;
    private javax.swing.JTextField txthargasat;
    private javax.swing.JTextField txtidtr;
    private javax.swing.JTextField txtjmlbeli;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnamapembeli;
    private javax.swing.JTextField txttglbeli;
    private javax.swing.JTextField txttotalharga;
    // End of variables declaration//GEN-END:variables
}
